### ISSUE TITLE
the window is too small on 4K screen on linux

### ISSUE THREAD

**Issue by carlhung** [pmacro/Suit#4]
I run on my xps 4K display.

![Screenshot from 2019-05-29 21-32-07](https://user-images.githubusercontent.com/8233639/58561345-7a799780-8259-11e9-8dae-dd1bba9ba4b5.png)

**Comment by pmacro** [comment]
I pushed some changes that I *think* should fix this.  Unfortunately, I don't have a 4k display that I can test this out on.  However, I could reproduce the broken behaviour when scaling the desktop, and that is now fixed.  If you have time to try this out and report back, I'd really appreciate it!

There's a remaining problem where the scaling is set once and not updated, so if you were to change your resolution with the app running (or move the app to another screen), it would stay its original size.

**Comment by pmacro** [comment]
By the way, be sure to `swift package update`, as this fix required an update to the X11 dependency.

**Comment by carlhung** [comment]
yes, it fixed. thanks
