### ISSUE TITLE
the window drifts away

### ISSUE THREAD

**Issue by carlhung** [pmacro/Suit#5]
when i double-clicked to hold the top bar to move the window.
the window drifted away from the mouse pointer.

the pic below, i was still holding the mouse button and moving the window.

![IMG_3183](https://user-images.githubusercontent.com/8233639/58561889-c547df00-825a-11e9-8e6f-af5fd67da3e9.jpg)

**Comment by pmacro** [comment]
Thanks for creating this issue.  I am aware of that problem.  It's towards the top of my list of things to fix, so hopefully I'll get to it soon.

**Comment by pmacro** [comment]
This should be fixed now.  Please let me know if the latest code doesn't resolve this for you!  Thanks.
