### ISSUE TITLE
Failed to build in macOS

### ISSUE THREAD

**Issue by muizidn** [pmacro/Suit#9]
When I try to build either using `build.sh` or `swift build` the compiler emits error,

```
/Suit/Sources/Linux/IconLoader.swift:2:8: error: no such module 'GD'
import GD
       ^
```

My machine is Mojave, Xcode10.2.1, Swift  5.0.1, SwiftPM14490.62.2

[UPDATE]

Turns out Linux folder isn't excluded when building in macOS

**Comment by pmacro** [comment]
Thanks for fixing this!
